options ls = 78 nocenter nodate nonumber ps = 55;
ods graphics off;
data lab4f17;
infile 'C:\Users\sarah\Downloads\PLANTF17.DAT' firstobs = 2;
do row = 1 to 10;
do plant = 1 to 4;
if      plant = 1 then name = 'Plant A';
else if plant = 2 then name = 'Plant B';
else if plant = 3 then name = 'Plant C';
else                   name = 'Plant D';
input dischrg @@;
output;
end;
end;
proc print noobs;
proc sort;
by plant;
proc means n mean var;
by plant;
var dischrg;
proc univariate normal;
ods select TestsForNormality;
by plant;
var dischrg;
proc glm;
class plant;
model dischrg = plant;
means plant /HOVTEST = bartlett;
means plant / Tukey;
run;
quit;
