options ls = 78 ps = 55 nocenter nodate;
data mhtest;
infile 'C:\Users\Sarah\Downloads\quality2s_w17 (2).dat' firstobs = 2;
do plant = 1 to 3;
     if plant = 1 then plant1 = 'Plant1';
else if plant = 2 then plant1 = 'Plant2';
else                   plant1 = 'Plant3';
do shift = 1 to 2;
if shift = 1 then shift1 = 'Day  ';
else              shift1 = 'Night';
do oper = 1 to 2;
if oper = 1 then oper1 = 'Shutdown   ';
else             oper1 = 'No Shutdown';
input wt @@;
output;
end;
end;
end;
proc print;
proc freq;
weight wt;
tables plant1*shift1*oper1/norow nocol cmh;
run;
quit;
