options nocenter nodate nonumber ls = 78 ps =55 formdlim = '#';
ods graohics off;
data dograces;
infile 'C:\Users\Sarah\Downloads\DOGRACE1S.DAT' firstobs =2;
do rows = 1 to 10;
do dog_name = 1 to 3;
     if dog_name = 1 then level = 'Trusty Dusty ';
else if dog_name = 2 then level = 'White Shadow ';
else                      level = 'Lakota Dakota';
input times @@;
output;
end;
end;
proc print;
proc sort;
by level;
proc print;
proc npar1way median;
class level;
var times;
run;
quit;
