options ls = 78 ps = 55 nocenter nodate nonumber;
data wait1;
title1 'Statistics 140 Lab #5, Winter 2017';
title2 'Sarah Ruckman';
infile 'C:\Users\Sarah\Downloads\WAITING_TIME_140.DAT' firstobs = 2;
input time;
proc print;
proc univariate mu0=15;
ods select TestsForLocation;
var time;
data stores;
infile 'C:\Users\Sarah\Downloads\GROCERY_140.dat' firstobs = 2;
input vons ralphs;
diff = vons-ralphs;
proc print;
proc univariate;
ods select TestsForLocation;
var diff;
run;
quit;
