options nocenter nodate nonumber ls = 78 ps = 55;
data food;
infile 'C:\Users\Sarah\Downloads\FRIEDMAN1.DAT' firstobs = 2;
do item1 = 1 to 6;
	 if item1 = 1 then item = 'bottled water';
else if item1 = 2 then item = 'sunscreen    ';
else if item1 = 3 then item = 'lunch meat   ';
else if item1 = 4 then item = 'bread        ';
else if item1 = 5 then item = 'condiments   ';
else                   item = 'cheese       ';
do store = 1 to 3;
	 if store = 1 then name = 'Vons      ';
else if store = 2 then name = 'Ralphs    ';
else                   name = 'Albertsons';
input price @@;
output;
end;
end;
proc print noobs;
proc freq;
tables item*store*price/cmh2 scores = rank noprint;
run;
quit;
